# Generated by Django 3.2.25 on 2024-03-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComusDis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comusctrlparsmodel',
            name='comus_dis_uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
