from map import generate_map
from FilterDepartment import deparment_information
from lmwl_filtering import plot_lmwl
from temporalseries import analyze_temporal_series
from departments_comparison import compare_deparments
from dataset_downloading import download_dataset
from siteinformation_downloading import download_site_information