# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs

__all__ = [
    'GetQualityProfilesResult',
    'AwaitableGetQualityProfilesResult',
    'get_quality_profiles',
    'get_quality_profiles_output',
]

@pulumi.output_type
class GetQualityProfilesResult:
    """
    A collection of values returned by getQualityProfiles.
    """
    def __init__(__self__, id=None, quality_profiles=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if quality_profiles and not isinstance(quality_profiles, list):
            raise TypeError("Expected argument 'quality_profiles' to be a list")
        pulumi.set(__self__, "quality_profiles", quality_profiles)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The ID of this resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="qualityProfiles")
    def quality_profiles(self) -> Sequence['outputs.GetQualityProfilesQualityProfileResult']:
        """
        Quality Profile list.
        """
        return pulumi.get(self, "quality_profiles")


class AwaitableGetQualityProfilesResult(GetQualityProfilesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetQualityProfilesResult(
            id=self.id,
            quality_profiles=self.quality_profiles)


def get_quality_profiles(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetQualityProfilesResult:
    """
    <!-- subcategory:Profiles -->List all available Quality Profiles.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_lidarr as lidarr

    example = lidarr.Profiles.get_quality_profiles()
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('lidarr:Profiles/getQualityProfiles:getQualityProfiles', __args__, opts=opts, typ=GetQualityProfilesResult).value

    return AwaitableGetQualityProfilesResult(
        id=pulumi.get(__ret__, 'id'),
        quality_profiles=pulumi.get(__ret__, 'quality_profiles'))


@_utilities.lift_output_func(get_quality_profiles)
def get_quality_profiles_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetQualityProfilesResult]:
    """
    <!-- subcategory:Profiles -->List all available Quality Profiles.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_lidarr as lidarr

    example = lidarr.Profiles.get_quality_profiles()
    ```
    """
    ...
