
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-30T15:19:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "113017f48374b8816efda23673d0476e6fd81674",
 "version": "1.25.0.post0.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
