# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'GetTagsDetailsTagResult',
]

@pulumi.output_type
class GetTagsDetailsTagResult(dict):
    def __init__(__self__, *,
                 application_ids: Sequence[int],
                 id: int,
                 indexer_ids: Sequence[int],
                 indexer_proxy_ids: Sequence[int],
                 label: str,
                 notification_ids: Sequence[int]):
        """
        :param Sequence[int] application_ids: List of associated applications.
        :param int id: Tags ID.
        :param Sequence[int] indexer_ids: List of associated indexers.
        :param Sequence[int] indexer_proxy_ids: List of associated indexer proxies.
        :param str label: Tags label.
        :param Sequence[int] notification_ids: List of associated notifications.
        """
        pulumi.set(__self__, "application_ids", application_ids)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "indexer_ids", indexer_ids)
        pulumi.set(__self__, "indexer_proxy_ids", indexer_proxy_ids)
        pulumi.set(__self__, "label", label)
        pulumi.set(__self__, "notification_ids", notification_ids)

    @property
    @pulumi.getter(name="applicationIds")
    def application_ids(self) -> Sequence[int]:
        """
        List of associated applications.
        """
        return pulumi.get(self, "application_ids")

    @property
    @pulumi.getter
    def id(self) -> int:
        """
        Tags ID.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="indexerIds")
    def indexer_ids(self) -> Sequence[int]:
        """
        List of associated indexers.
        """
        return pulumi.get(self, "indexer_ids")

    @property
    @pulumi.getter(name="indexerProxyIds")
    def indexer_proxy_ids(self) -> Sequence[int]:
        """
        List of associated indexer proxies.
        """
        return pulumi.get(self, "indexer_proxy_ids")

    @property
    @pulumi.getter
    def label(self) -> str:
        """
        Tags label.
        """
        return pulumi.get(self, "label")

    @property
    @pulumi.getter(name="notificationIds")
    def notification_ids(self) -> Sequence[int]:
        """
        List of associated notifications.
        """
        return pulumi.get(self, "notification_ids")


