import sys
from zfx.zprint import en_print
from zfx.zprint import dis_print
from zfx.zprint import zprint
from zfx.zprint import zdebug
from zfx.zmodule_240414A import 延迟
from zfx.zmodule_240414A import 文本_到大写
from zfx.zmodule_240414A import 文本_到小写
from zfx.zmodule_240414A import 文本_颠倒
from zfx.zmodule_240414A import 文本_分割文本
from zfx.zmodule_240414A import 文本_加密
from zfx.zmodule_240414A import 文本_解密
from zfx.zmodule_240414A import 文本_取出文本中汉字
from zfx.zmodule_240414A import 文本_取出现次数
from zfx.zmodule_240414A import 文本_取出中间文本
from zfx.zmodule_240414A import 文本_取随机字符
from zfx.zmodule_240414A import 文本_取文本所在行
from zfx.zmodule_240414A import 文本_取行数
from zfx.zmodule_240414A import 文本_取右边
from zfx.zmodule_240414A import 文本_取长度
from zfx.zmodule_240414A import 文本_取指定变量文本行
from zfx.zmodule_240414A import 文本_取左边
from zfx.zmodule_240414A import 文本_替换行内容
from zfx.zmodule_240414A import 文本区分_只取符号
from zfx.zmodule_240414A import 文本区分_只取汉字
from zfx.zmodule_240414A import 文本区分_只取数字
from zfx.系统_取系统现行时间 import 系统_取系统现行时间
from zfx.系统_取CPU型号 import 系统_取CPU型号
from zfx.系统_置剪辑版内容 import 系统_置剪辑版内容
from zfx.系统_取剪辑版内容 import 系统_取剪辑版内容
from zfx.系统任务计划_删除 import 系统任务计划_删除
from zfx.系统任务计划_遍历名称 import 系统任务计划_遍历名称
from zfx.g2g_account_list import g2g_account_list
from zfx.g2g_account_list_s import g2g_account_list_s