
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-30T18:55:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "369e50353db36f14872a4af82e17362f91c5d712",
 "version": "1.4.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
