# Generated by Django 3.2.16 on 2024-04-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberpress_client', '0002_auto_20221219_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpresseventlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
