# Autogenerated by Astropy-affiliated package speclite's setup.py on 2024-04-30 21:28:34 UTC
import datetime

version = "0.19"
githash = "f77d73c496d49e6c29b080962cb3650474104462"


major = 0
minor = 19
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2024, 4, 30, 21, 28, 34)
debug = False

astropy_helpers_version = "4.0.1"
