# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs

__all__ = [
    'GetAutoTagsResult',
    'AwaitableGetAutoTagsResult',
    'get_auto_tags',
    'get_auto_tags_output',
]

@pulumi.output_type
class GetAutoTagsResult:
    """
    A collection of values returned by getAutoTags.
    """
    def __init__(__self__, auto_tags=None, id=None):
        if auto_tags and not isinstance(auto_tags, list):
            raise TypeError("Expected argument 'auto_tags' to be a list")
        pulumi.set(__self__, "auto_tags", auto_tags)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @property
    @pulumi.getter(name="autoTags")
    def auto_tags(self) -> Sequence['outputs.GetAutoTagsAutoTagResult']:
        """
        Auto Tag list.
        """
        return pulumi.get(self, "auto_tags")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The ID of this resource.
        """
        return pulumi.get(self, "id")


class AwaitableGetAutoTagsResult(GetAutoTagsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAutoTagsResult(
            auto_tags=self.auto_tags,
            id=self.id)


def get_auto_tags(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAutoTagsResult:
    """
    <!-- subcategory:Tags -->
    List all available Auto Tags.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_sonarr as sonarr

    example = sonarr.Tags.get_auto_tags()
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('sonarr:Tags/getAutoTags:getAutoTags', __args__, opts=opts, typ=GetAutoTagsResult).value

    return AwaitableGetAutoTagsResult(
        auto_tags=pulumi.get(__ret__, 'auto_tags'),
        id=pulumi.get(__ret__, 'id'))


@_utilities.lift_output_func(get_auto_tags)
def get_auto_tags_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetAutoTagsResult]:
    """
    <!-- subcategory:Tags -->
    List all available Auto Tags.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_sonarr as sonarr

    example = sonarr.Tags.get_auto_tags()
    ```
    """
    ...
