NEW_WF_PAYLOAD = """{
    "type": "taskWorkflow",
    "actions": {
        "abortActions": [],
        "emailNotifications": [],
        "setVariableActions": [],
        "snmpNotifications": [],
        "systemOperations": []
    },
    "calculateCp": false,
    "calendar": null,
    "cpDuration": null,
    "cpDurationUnit": "Minutes",
    "customField1": {
        "label": null,
        "value": null
    },
    "customField2": {
        "label": null,
        "value": null
    },
    "efDayConstraint": "None",
    "efDuration": "00:00:00:00",
    "efEnabled": false,
    "efNthAmount": 5,
    "efOffsetDuration": null,
    "efOffsetDurationUnit": "Minutes",
    "efOffsetPercentage": 0,
    "efOffsetType": "Percentage",
    "efTime": "00:00",
    "efType": "Time",
    "exclusiveTasks": [],
    "executionRestriction": "None",
    "exportReleaseLevel": "7.2.0.0",
    "exportTable": "ops_task_workflow",
    "firstRun": "",
    "holdResources": false,
    "lastRun": "",
    "layoutOption": "-- None --",
    "lfDayConstraint": "None",
    "lfDuration": "00:00:00:00",
    "lfEnabled": false,
    "lfNthAmount": 5,
    "lfOffsetDuration": null,
    "lfOffsetDurationUnit": "Minutes",
    "lfOffsetPercentage": 0,
    "lfOffsetType": "Percentage",
    "lfTime": "00:00",
    "lfType": "Time",
    "logLevel": "Inherited",
    "lsDayConstraint": "None",
    "lsDuration": "00:00:00:00",
    "lsEnabled": false,
    "lsNthAmount": 5,
    "lsTime": "00:00",
    "lsType": "Time",
    "name": "change_me",
    "notes": [],
    "numberOfTasks": null,
    "opswiseGroups": [],
    "overrideCalendar": false,
    "resPriority": 10,
    "resolveNameImmediately": false,
    "restrictionPeriod": "None",
    "restrictionPeriodAfterDate": null,
    "restrictionPeriodAfterTime": null,
    "restrictionPeriodBeforeDate": null,
    "restrictionPeriodBeforeTime": null,
    "restrictionPeriodDateList": [],
    "retainSysIds": true,
    "runCount": 0,
    "runCriteria": [],
    "runTime": 0,
    "skippedOption": "Show Skipped",
    "startHeld": false,
    "startHeldReason": null,
    "stepActions": [],
    "stepConditions": [],
    "summary": null,
    "timeZonePref": "-- System Default --",
    "twDelayAmount": null,
    "twDelayDuration": "00:00:00:00",
    "twDelayType": "None",
    "twWaitAmount": null,
    "twWaitDayConstraint": "None",
    "twWaitDuration": "00:00:00:00",
    "twWaitTime": "00:00",
    "twWaitType": "None",
    "twWorkflowOnly": "-- System Default --",
    "userEstimatedDuration": null,
    "variables": [],
    "version": 1,
    "virtualResources": [],
    "workflowEdges": [],
    "workflowVertices": []
}"""

VARIABLE_PAYLOAD = {
    "allowEmptyOption" : False,
    "allowUnlistedOption" : False,
    "description" : None,
    "name" : "",
    "options" : [ ],
    "value" : ""
  }

SQL_TASK_SET_VARIABLE_ACTION_PAYLOAD = {
      "description" : None,
      "exitCodes" : None,
      "notificationOption" : "Operation Failure",
      "notifyOnEarlyFinish" : False,
      "notifyOnLateFinish" : False,
      "notifyOnLateStart" : False,
      "notifyOnProjectedLate" : False,
      "status" : "Success",
      "variableName" : "",
      "variableScope" : "Global",
      "variableValue" : "${_resultsColumnByNo('',1,1)}"
    }