
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-30T14:37:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4cdaa7c4a4b6db39f25c873f4901fc5b2a052eca",
 "version": "1.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
