# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .base import BaseModel
from .agreement import Agreement
from .page_info_without_cursor import PageInfoWithoutCursor


@JsonMap({})
class AgreementListContainer(BaseModel):
    """AgreementListContainer

    :param data: data
    :type data: List[Agreement]
    :param page: page, defaults to None
    :type page: PageInfoWithoutCursor, optional
    """

    def __init__(self, data: List[Agreement], page: PageInfoWithoutCursor = None):
        self.data = self._define_list(data, Agreement)
        if page is not None:
            self.page = self._define_object(page, PageInfoWithoutCursor)
