# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .base import BaseModel
from .contract_to_create_payg_tasks import ContractToCreatePaygTasks


@JsonMap({})
class ContractToCreateContainerPaygTasks(BaseModel):
    """ContractToCreateContainerPaygTasks

    :param data: data
    :type data: ContractToCreatePaygTasks
    """

    def __init__(self, data: ContractToCreatePaygTasks):
        self.data = self._define_object(data, ContractToCreatePaygTasks)
