# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .base import BaseModel
from .gp_employee_information_update_data import GpEmployeeInformationUpdateData


@JsonMap({})
class GpEmployeeInformationToUpdateContainer(BaseModel):
    """GpEmployeeInformationToUpdateContainer

    :param data: data
    :type data: GpEmployeeInformationUpdateData
    """

    def __init__(self, data: GpEmployeeInformationUpdateData):
        self.data = self._define_object(data, GpEmployeeInformationUpdateData)
