# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_whisparr.config as __config
    config = __config
    import pulumi_whisparr.downloadclients as __downloadclients
    downloadclients = __downloadclients
    import pulumi_whisparr.importlists as __importlists
    importlists = __importlists
    import pulumi_whisparr.indexers as __indexers
    indexers = __indexers
    import pulumi_whisparr.languages as __languages
    languages = __languages
    import pulumi_whisparr.mediamanagement as __mediamanagement
    mediamanagement = __mediamanagement
    import pulumi_whisparr.metadata as __metadata
    metadata = __metadata
    import pulumi_whisparr.movies as __movies
    movies = __movies
    import pulumi_whisparr.notifications as __notifications
    notifications = __notifications
    import pulumi_whisparr.profiles as __profiles
    profiles = __profiles
    import pulumi_whisparr.system as __system
    system = __system
    import pulumi_whisparr.tags as __tags
    tags = __tags
else:
    config = _utilities.lazy_import('pulumi_whisparr.config')
    downloadclients = _utilities.lazy_import('pulumi_whisparr.downloadclients')
    importlists = _utilities.lazy_import('pulumi_whisparr.importlists')
    indexers = _utilities.lazy_import('pulumi_whisparr.indexers')
    languages = _utilities.lazy_import('pulumi_whisparr.languages')
    mediamanagement = _utilities.lazy_import('pulumi_whisparr.mediamanagement')
    metadata = _utilities.lazy_import('pulumi_whisparr.metadata')
    movies = _utilities.lazy_import('pulumi_whisparr.movies')
    notifications = _utilities.lazy_import('pulumi_whisparr.notifications')
    profiles = _utilities.lazy_import('pulumi_whisparr.profiles')
    system = _utilities.lazy_import('pulumi_whisparr.system')
    tags = _utilities.lazy_import('pulumi_whisparr.tags')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/aria2",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/aria2:Aria2": "Aria2"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/config",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/config:Config": "Config"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/deluge",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/deluge:Deluge": "Deluge"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/downloadClient",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/downloadClient:DownloadClient": "DownloadClient"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/flood",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/flood:Flood": "Flood"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/hadouken",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/hadouken:Hadouken": "Hadouken"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/nzbget",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/nzbget:Nzbget": "Nzbget"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/nzbvortex",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/nzbvortex:Nzbvortex": "Nzbvortex"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/pneumatic",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/pneumatic:Pneumatic": "Pneumatic"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/qbittorrent",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/qbittorrent:Qbittorrent": "Qbittorrent"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/remotePathMapping",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/remotePathMapping:RemotePathMapping": "RemotePathMapping"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/rtorrent",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/rtorrent:Rtorrent": "Rtorrent"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/sabnzbd",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/sabnzbd:Sabnzbd": "Sabnzbd"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/torrentBlackhole",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/torrentBlackhole:TorrentBlackhole": "TorrentBlackhole"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/torrentDownloadStation",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/torrentDownloadStation:TorrentDownloadStation": "TorrentDownloadStation"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/transmission",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/transmission:Transmission": "Transmission"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/usenetBlackhole",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/usenetBlackhole:UsenetBlackhole": "UsenetBlackhole"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/usenetDownloadStation",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/usenetDownloadStation:UsenetDownloadStation": "UsenetDownloadStation"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/utorrent",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/utorrent:Utorrent": "Utorrent"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "DownloadClients/vuze",
  "fqn": "pulumi_whisparr.downloadclients",
  "classes": {
   "whisparr:DownloadClients/vuze:Vuze": "Vuze"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/config",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/config:Config": "Config"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/couchPotato",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/couchPotato:CouchPotato": "CouchPotato"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/custom",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/custom:Custom": "Custom"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/exclusion",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/exclusion:Exclusion": "Exclusion"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/imdb",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/imdb:Imdb": "Imdb"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/importList",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/importList:ImportList": "ImportList"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/plex",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/plex:Plex": "Plex"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/rss",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/rss:Rss": "Rss"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/stevenlu",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/stevenlu:Stevenlu": "Stevenlu"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/stevenlu2",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/stevenlu2:Stevenlu2": "Stevenlu2"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/tmdbCollection",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/tmdbCollection:TmdbCollection": "TmdbCollection"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/tmdbCompany",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/tmdbCompany:TmdbCompany": "TmdbCompany"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/tmdbKeyword",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/tmdbKeyword:TmdbKeyword": "TmdbKeyword"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/tmdbList",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/tmdbList:TmdbList": "TmdbList"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/tmdbPerson",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/tmdbPerson:TmdbPerson": "TmdbPerson"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/tmdbPopular",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/tmdbPopular:TmdbPopular": "TmdbPopular"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/tmdbUser",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/tmdbUser:TmdbUser": "TmdbUser"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/traktList",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/traktList:TraktList": "TraktList"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/traktPopular",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/traktPopular:TraktPopular": "TraktPopular"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/traktUser",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/traktUser:TraktUser": "TraktUser"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "ImportLists/whisparr",
  "fqn": "pulumi_whisparr.importlists",
  "classes": {
   "whisparr:ImportLists/whisparr:Whisparr": "Whisparr"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/config",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/config:Config": "Config"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/filelist",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/filelist:Filelist": "Filelist"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/hdbits",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/hdbits:Hdbits": "Hdbits"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/indexer",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/indexer:Indexer": "Indexer"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/iptorrents",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/iptorrents:Iptorrents": "Iptorrents"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/newznab",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/newznab:Newznab": "Newznab"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/nyaa",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/nyaa:Nyaa": "Nyaa"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/omgwtfnzbs",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/omgwtfnzbs:Omgwtfnzbs": "Omgwtfnzbs"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/rarbg",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/rarbg:Rarbg": "Rarbg"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/restriction",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/restriction:Restriction": "Restriction"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/torrentPotato",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/torrentPotato:TorrentPotato": "TorrentPotato"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/torrentRss",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/torrentRss:TorrentRss": "TorrentRss"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Indexers/torznab",
  "fqn": "pulumi_whisparr.indexers",
  "classes": {
   "whisparr:Indexers/torznab:Torznab": "Torznab"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "MediaManagement/mediaManagement",
  "fqn": "pulumi_whisparr.mediamanagement",
  "classes": {
   "whisparr:MediaManagement/mediaManagement:MediaManagement": "MediaManagement"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "MediaManagement/naming",
  "fqn": "pulumi_whisparr.mediamanagement",
  "classes": {
   "whisparr:MediaManagement/naming:Naming": "Naming"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "MediaManagement/rootFolder",
  "fqn": "pulumi_whisparr.mediamanagement",
  "classes": {
   "whisparr:MediaManagement/rootFolder:RootFolder": "RootFolder"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Metadata/config",
  "fqn": "pulumi_whisparr.metadata",
  "classes": {
   "whisparr:Metadata/config:Config": "Config"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Metadata/emby",
  "fqn": "pulumi_whisparr.metadata",
  "classes": {
   "whisparr:Metadata/emby:Emby": "Emby"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Metadata/kodi",
  "fqn": "pulumi_whisparr.metadata",
  "classes": {
   "whisparr:Metadata/kodi:Kodi": "Kodi"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Metadata/metadata",
  "fqn": "pulumi_whisparr.metadata",
  "classes": {
   "whisparr:Metadata/metadata:Metadata": "Metadata"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Metadata/roksbox",
  "fqn": "pulumi_whisparr.metadata",
  "classes": {
   "whisparr:Metadata/roksbox:Roksbox": "Roksbox"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Metadata/wdtv",
  "fqn": "pulumi_whisparr.metadata",
  "classes": {
   "whisparr:Metadata/wdtv:Wdtv": "Wdtv"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Movies/movie",
  "fqn": "pulumi_whisparr.movies",
  "classes": {
   "whisparr:Movies/movie:Movie": "Movie"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/boxcar",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/boxcar:Boxcar": "Boxcar"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/customScript",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/customScript:CustomScript": "CustomScript"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/discord",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/discord:Discord": "Discord"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/email",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/email:Email": "Email"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/emby",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/emby:Emby": "Emby"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/gotify",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/gotify:Gotify": "Gotify"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/join",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/join:Join": "Join"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/kodi",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/kodi:Kodi": "Kodi"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/mailgun",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/mailgun:Mailgun": "Mailgun"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/notifiarr",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/notifiarr:Notifiarr": "Notifiarr"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/notification",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/notification:Notification": "Notification"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/plex",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/plex:Plex": "Plex"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/prowl",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/prowl:Prowl": "Prowl"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/pushbullet",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/pushbullet:Pushbullet": "Pushbullet"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/pushover",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/pushover:Pushover": "Pushover"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/sendgrid",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/sendgrid:Sendgrid": "Sendgrid"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/simplepush",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/simplepush:Simplepush": "Simplepush"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/slack",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/slack:Slack": "Slack"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/synologyIndexer",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/synologyIndexer:SynologyIndexer": "SynologyIndexer"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/telegram",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/telegram:Telegram": "Telegram"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/trakt",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/trakt:Trakt": "Trakt"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/twitter",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/twitter:Twitter": "Twitter"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Notifications/webhook",
  "fqn": "pulumi_whisparr.notifications",
  "classes": {
   "whisparr:Notifications/webhook:Webhook": "Webhook"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Profiles/customFormat",
  "fqn": "pulumi_whisparr.profiles",
  "classes": {
   "whisparr:Profiles/customFormat:CustomFormat": "CustomFormat"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Profiles/definition",
  "fqn": "pulumi_whisparr.profiles",
  "classes": {
   "whisparr:Profiles/definition:Definition": "Definition"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Profiles/delayProfile",
  "fqn": "pulumi_whisparr.profiles",
  "classes": {
   "whisparr:Profiles/delayProfile:DelayProfile": "DelayProfile"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Profiles/profile",
  "fqn": "pulumi_whisparr.profiles",
  "classes": {
   "whisparr:Profiles/profile:Profile": "Profile"
  }
 },
 {
  "pkg": "whisparr",
  "mod": "Tags/tag",
  "fqn": "pulumi_whisparr.tags",
  "classes": {
   "whisparr:Tags/tag:Tag": "Tag"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "whisparr",
  "token": "pulumi:providers:whisparr",
  "fqn": "pulumi_whisparr",
  "class": "Provider"
 }
]
"""
)
