# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'GetSchemasResult',
    'AwaitableGetSchemasResult',
    'get_schemas',
    'get_schemas_output',
]

@pulumi.output_type
class GetSchemasResult:
    """
    A collection of values returned by getSchemas.
    """
    def __init__(__self__, id=None, indexer_schemas=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if indexer_schemas and not isinstance(indexer_schemas, list):
            raise TypeError("Expected argument 'indexer_schemas' to be a list")
        pulumi.set(__self__, "indexer_schemas", indexer_schemas)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The ID of this resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="indexerSchemas")
    def indexer_schemas(self) -> Sequence[str]:
        """
        Indexer name list.
        """
        return pulumi.get(self, "indexer_schemas")


class AwaitableGetSchemasResult(GetSchemasResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSchemasResult(
            id=self.id,
            indexer_schemas=self.indexer_schemas)


def get_schemas(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSchemasResult:
    """
    <!-- subcategory:Indexers -->List all available Indexer Schemas.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_prowlarr as prowlarr

    example = prowlarr.Indexers.get_schemas()
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('prowlarr:Indexers/getSchemas:getSchemas', __args__, opts=opts, typ=GetSchemasResult).value

    return AwaitableGetSchemasResult(
        id=pulumi.get(__ret__, 'id'),
        indexer_schemas=pulumi.get(__ret__, 'indexer_schemas'))


@_utilities.lift_output_func(get_schemas)
def get_schemas_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetSchemasResult]:
    """
    <!-- subcategory:Indexers -->List all available Indexer Schemas.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_prowlarr as prowlarr

    example = prowlarr.Indexers.get_schemas()
    ```
    """
    ...
