# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = ['SignalArgs', 'Signal']

@pulumi.input_type
class SignalArgs:
    def __init__(__self__, *,
                 host: pulumi.Input[str],
                 receiver_id: pulumi.Input[str],
                 sender_number: pulumi.Input[str],
                 auth_password: Optional[pulumi.Input[str]] = None,
                 auth_username: Optional[pulumi.Input[str]] = None,
                 include_health_warnings: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 on_application_update: Optional[pulumi.Input[bool]] = None,
                 on_download: Optional[pulumi.Input[bool]] = None,
                 on_episode_file_delete: Optional[pulumi.Input[bool]] = None,
                 on_episode_file_delete_for_upgrade: Optional[pulumi.Input[bool]] = None,
                 on_grab: Optional[pulumi.Input[bool]] = None,
                 on_health_issue: Optional[pulumi.Input[bool]] = None,
                 on_health_restored: Optional[pulumi.Input[bool]] = None,
                 on_manual_interaction_required: Optional[pulumi.Input[bool]] = None,
                 on_series_add: Optional[pulumi.Input[bool]] = None,
                 on_series_delete: Optional[pulumi.Input[bool]] = None,
                 on_upgrade: Optional[pulumi.Input[bool]] = None,
                 port: Optional[pulumi.Input[int]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 use_ssl: Optional[pulumi.Input[bool]] = None):
        """
        The set of arguments for constructing a Signal resource.
        :param pulumi.Input[str] host: Host.
        :param pulumi.Input[str] receiver_id: Receiver ID.
        :param pulumi.Input[str] sender_number: Sender Number.
        :param pulumi.Input[str] auth_password: Password.
        :param pulumi.Input[str] auth_username: Username.
        :param pulumi.Input[bool] include_health_warnings: Include health warnings.
        :param pulumi.Input[str] name: NotificationSignal name.
        :param pulumi.Input[bool] on_application_update: On application update flag.
        :param pulumi.Input[bool] on_download: On download flag.
        :param pulumi.Input[bool] on_episode_file_delete: On episode file delete flag.
        :param pulumi.Input[bool] on_episode_file_delete_for_upgrade: On episode file delete for upgrade flag.
        :param pulumi.Input[bool] on_grab: On grab flag.
        :param pulumi.Input[bool] on_health_issue: On health issue flag.
        :param pulumi.Input[bool] on_health_restored: On health restored flag.
        :param pulumi.Input[bool] on_manual_interaction_required: On manual interaction required flag.
        :param pulumi.Input[bool] on_series_add: On series add flag.
        :param pulumi.Input[bool] on_series_delete: On series delete flag.
        :param pulumi.Input[bool] on_upgrade: On upgrade flag.
        :param pulumi.Input[int] port: Port.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] tags: List of associated tags.
        :param pulumi.Input[bool] use_ssl: Use SSL flag.
        """
        pulumi.set(__self__, "host", host)
        pulumi.set(__self__, "receiver_id", receiver_id)
        pulumi.set(__self__, "sender_number", sender_number)
        if auth_password is not None:
            pulumi.set(__self__, "auth_password", auth_password)
        if auth_username is not None:
            pulumi.set(__self__, "auth_username", auth_username)
        if include_health_warnings is not None:
            pulumi.set(__self__, "include_health_warnings", include_health_warnings)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if on_application_update is not None:
            pulumi.set(__self__, "on_application_update", on_application_update)
        if on_download is not None:
            pulumi.set(__self__, "on_download", on_download)
        if on_episode_file_delete is not None:
            pulumi.set(__self__, "on_episode_file_delete", on_episode_file_delete)
        if on_episode_file_delete_for_upgrade is not None:
            pulumi.set(__self__, "on_episode_file_delete_for_upgrade", on_episode_file_delete_for_upgrade)
        if on_grab is not None:
            pulumi.set(__self__, "on_grab", on_grab)
        if on_health_issue is not None:
            pulumi.set(__self__, "on_health_issue", on_health_issue)
        if on_health_restored is not None:
            pulumi.set(__self__, "on_health_restored", on_health_restored)
        if on_manual_interaction_required is not None:
            pulumi.set(__self__, "on_manual_interaction_required", on_manual_interaction_required)
        if on_series_add is not None:
            pulumi.set(__self__, "on_series_add", on_series_add)
        if on_series_delete is not None:
            pulumi.set(__self__, "on_series_delete", on_series_delete)
        if on_upgrade is not None:
            pulumi.set(__self__, "on_upgrade", on_upgrade)
        if port is not None:
            pulumi.set(__self__, "port", port)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if use_ssl is not None:
            pulumi.set(__self__, "use_ssl", use_ssl)

    @property
    @pulumi.getter
    def host(self) -> pulumi.Input[str]:
        """
        Host.
        """
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: pulumi.Input[str]):
        pulumi.set(self, "host", value)

    @property
    @pulumi.getter(name="receiverId")
    def receiver_id(self) -> pulumi.Input[str]:
        """
        Receiver ID.
        """
        return pulumi.get(self, "receiver_id")

    @receiver_id.setter
    def receiver_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "receiver_id", value)

    @property
    @pulumi.getter(name="senderNumber")
    def sender_number(self) -> pulumi.Input[str]:
        """
        Sender Number.
        """
        return pulumi.get(self, "sender_number")

    @sender_number.setter
    def sender_number(self, value: pulumi.Input[str]):
        pulumi.set(self, "sender_number", value)

    @property
    @pulumi.getter(name="authPassword")
    def auth_password(self) -> Optional[pulumi.Input[str]]:
        """
        Password.
        """
        return pulumi.get(self, "auth_password")

    @auth_password.setter
    def auth_password(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "auth_password", value)

    @property
    @pulumi.getter(name="authUsername")
    def auth_username(self) -> Optional[pulumi.Input[str]]:
        """
        Username.
        """
        return pulumi.get(self, "auth_username")

    @auth_username.setter
    def auth_username(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "auth_username", value)

    @property
    @pulumi.getter(name="includeHealthWarnings")
    def include_health_warnings(self) -> Optional[pulumi.Input[bool]]:
        """
        Include health warnings.
        """
        return pulumi.get(self, "include_health_warnings")

    @include_health_warnings.setter
    def include_health_warnings(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "include_health_warnings", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        NotificationSignal name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="onApplicationUpdate")
    def on_application_update(self) -> Optional[pulumi.Input[bool]]:
        """
        On application update flag.
        """
        return pulumi.get(self, "on_application_update")

    @on_application_update.setter
    def on_application_update(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_application_update", value)

    @property
    @pulumi.getter(name="onDownload")
    def on_download(self) -> Optional[pulumi.Input[bool]]:
        """
        On download flag.
        """
        return pulumi.get(self, "on_download")

    @on_download.setter
    def on_download(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_download", value)

    @property
    @pulumi.getter(name="onEpisodeFileDelete")
    def on_episode_file_delete(self) -> Optional[pulumi.Input[bool]]:
        """
        On episode file delete flag.
        """
        return pulumi.get(self, "on_episode_file_delete")

    @on_episode_file_delete.setter
    def on_episode_file_delete(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_episode_file_delete", value)

    @property
    @pulumi.getter(name="onEpisodeFileDeleteForUpgrade")
    def on_episode_file_delete_for_upgrade(self) -> Optional[pulumi.Input[bool]]:
        """
        On episode file delete for upgrade flag.
        """
        return pulumi.get(self, "on_episode_file_delete_for_upgrade")

    @on_episode_file_delete_for_upgrade.setter
    def on_episode_file_delete_for_upgrade(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_episode_file_delete_for_upgrade", value)

    @property
    @pulumi.getter(name="onGrab")
    def on_grab(self) -> Optional[pulumi.Input[bool]]:
        """
        On grab flag.
        """
        return pulumi.get(self, "on_grab")

    @on_grab.setter
    def on_grab(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_grab", value)

    @property
    @pulumi.getter(name="onHealthIssue")
    def on_health_issue(self) -> Optional[pulumi.Input[bool]]:
        """
        On health issue flag.
        """
        return pulumi.get(self, "on_health_issue")

    @on_health_issue.setter
    def on_health_issue(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_health_issue", value)

    @property
    @pulumi.getter(name="onHealthRestored")
    def on_health_restored(self) -> Optional[pulumi.Input[bool]]:
        """
        On health restored flag.
        """
        return pulumi.get(self, "on_health_restored")

    @on_health_restored.setter
    def on_health_restored(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_health_restored", value)

    @property
    @pulumi.getter(name="onManualInteractionRequired")
    def on_manual_interaction_required(self) -> Optional[pulumi.Input[bool]]:
        """
        On manual interaction required flag.
        """
        return pulumi.get(self, "on_manual_interaction_required")

    @on_manual_interaction_required.setter
    def on_manual_interaction_required(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_manual_interaction_required", value)

    @property
    @pulumi.getter(name="onSeriesAdd")
    def on_series_add(self) -> Optional[pulumi.Input[bool]]:
        """
        On series add flag.
        """
        return pulumi.get(self, "on_series_add")

    @on_series_add.setter
    def on_series_add(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_series_add", value)

    @property
    @pulumi.getter(name="onSeriesDelete")
    def on_series_delete(self) -> Optional[pulumi.Input[bool]]:
        """
        On series delete flag.
        """
        return pulumi.get(self, "on_series_delete")

    @on_series_delete.setter
    def on_series_delete(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_series_delete", value)

    @property
    @pulumi.getter(name="onUpgrade")
    def on_upgrade(self) -> Optional[pulumi.Input[bool]]:
        """
        On upgrade flag.
        """
        return pulumi.get(self, "on_upgrade")

    @on_upgrade.setter
    def on_upgrade(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_upgrade", value)

    @property
    @pulumi.getter
    def port(self) -> Optional[pulumi.Input[int]]:
        """
        Port.
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "port", value)

    @property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]:
        """
        List of associated tags.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]):
        pulumi.set(self, "tags", value)

    @property
    @pulumi.getter(name="useSsl")
    def use_ssl(self) -> Optional[pulumi.Input[bool]]:
        """
        Use SSL flag.
        """
        return pulumi.get(self, "use_ssl")

    @use_ssl.setter
    def use_ssl(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "use_ssl", value)


@pulumi.input_type
class _SignalState:
    def __init__(__self__, *,
                 auth_password: Optional[pulumi.Input[str]] = None,
                 auth_username: Optional[pulumi.Input[str]] = None,
                 host: Optional[pulumi.Input[str]] = None,
                 include_health_warnings: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 on_application_update: Optional[pulumi.Input[bool]] = None,
                 on_download: Optional[pulumi.Input[bool]] = None,
                 on_episode_file_delete: Optional[pulumi.Input[bool]] = None,
                 on_episode_file_delete_for_upgrade: Optional[pulumi.Input[bool]] = None,
                 on_grab: Optional[pulumi.Input[bool]] = None,
                 on_health_issue: Optional[pulumi.Input[bool]] = None,
                 on_health_restored: Optional[pulumi.Input[bool]] = None,
                 on_manual_interaction_required: Optional[pulumi.Input[bool]] = None,
                 on_series_add: Optional[pulumi.Input[bool]] = None,
                 on_series_delete: Optional[pulumi.Input[bool]] = None,
                 on_upgrade: Optional[pulumi.Input[bool]] = None,
                 port: Optional[pulumi.Input[int]] = None,
                 receiver_id: Optional[pulumi.Input[str]] = None,
                 sender_number: Optional[pulumi.Input[str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 use_ssl: Optional[pulumi.Input[bool]] = None):
        """
        Input properties used for looking up and filtering Signal resources.
        :param pulumi.Input[str] auth_password: Password.
        :param pulumi.Input[str] auth_username: Username.
        :param pulumi.Input[str] host: Host.
        :param pulumi.Input[bool] include_health_warnings: Include health warnings.
        :param pulumi.Input[str] name: NotificationSignal name.
        :param pulumi.Input[bool] on_application_update: On application update flag.
        :param pulumi.Input[bool] on_download: On download flag.
        :param pulumi.Input[bool] on_episode_file_delete: On episode file delete flag.
        :param pulumi.Input[bool] on_episode_file_delete_for_upgrade: On episode file delete for upgrade flag.
        :param pulumi.Input[bool] on_grab: On grab flag.
        :param pulumi.Input[bool] on_health_issue: On health issue flag.
        :param pulumi.Input[bool] on_health_restored: On health restored flag.
        :param pulumi.Input[bool] on_manual_interaction_required: On manual interaction required flag.
        :param pulumi.Input[bool] on_series_add: On series add flag.
        :param pulumi.Input[bool] on_series_delete: On series delete flag.
        :param pulumi.Input[bool] on_upgrade: On upgrade flag.
        :param pulumi.Input[int] port: Port.
        :param pulumi.Input[str] receiver_id: Receiver ID.
        :param pulumi.Input[str] sender_number: Sender Number.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] tags: List of associated tags.
        :param pulumi.Input[bool] use_ssl: Use SSL flag.
        """
        if auth_password is not None:
            pulumi.set(__self__, "auth_password", auth_password)
        if auth_username is not None:
            pulumi.set(__self__, "auth_username", auth_username)
        if host is not None:
            pulumi.set(__self__, "host", host)
        if include_health_warnings is not None:
            pulumi.set(__self__, "include_health_warnings", include_health_warnings)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if on_application_update is not None:
            pulumi.set(__self__, "on_application_update", on_application_update)
        if on_download is not None:
            pulumi.set(__self__, "on_download", on_download)
        if on_episode_file_delete is not None:
            pulumi.set(__self__, "on_episode_file_delete", on_episode_file_delete)
        if on_episode_file_delete_for_upgrade is not None:
            pulumi.set(__self__, "on_episode_file_delete_for_upgrade", on_episode_file_delete_for_upgrade)
        if on_grab is not None:
            pulumi.set(__self__, "on_grab", on_grab)
        if on_health_issue is not None:
            pulumi.set(__self__, "on_health_issue", on_health_issue)
        if on_health_restored is not None:
            pulumi.set(__self__, "on_health_restored", on_health_restored)
        if on_manual_interaction_required is not None:
            pulumi.set(__self__, "on_manual_interaction_required", on_manual_interaction_required)
        if on_series_add is not None:
            pulumi.set(__self__, "on_series_add", on_series_add)
        if on_series_delete is not None:
            pulumi.set(__self__, "on_series_delete", on_series_delete)
        if on_upgrade is not None:
            pulumi.set(__self__, "on_upgrade", on_upgrade)
        if port is not None:
            pulumi.set(__self__, "port", port)
        if receiver_id is not None:
            pulumi.set(__self__, "receiver_id", receiver_id)
        if sender_number is not None:
            pulumi.set(__self__, "sender_number", sender_number)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if use_ssl is not None:
            pulumi.set(__self__, "use_ssl", use_ssl)

    @property
    @pulumi.getter(name="authPassword")
    def auth_password(self) -> Optional[pulumi.Input[str]]:
        """
        Password.
        """
        return pulumi.get(self, "auth_password")

    @auth_password.setter
    def auth_password(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "auth_password", value)

    @property
    @pulumi.getter(name="authUsername")
    def auth_username(self) -> Optional[pulumi.Input[str]]:
        """
        Username.
        """
        return pulumi.get(self, "auth_username")

    @auth_username.setter
    def auth_username(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "auth_username", value)

    @property
    @pulumi.getter
    def host(self) -> Optional[pulumi.Input[str]]:
        """
        Host.
        """
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "host", value)

    @property
    @pulumi.getter(name="includeHealthWarnings")
    def include_health_warnings(self) -> Optional[pulumi.Input[bool]]:
        """
        Include health warnings.
        """
        return pulumi.get(self, "include_health_warnings")

    @include_health_warnings.setter
    def include_health_warnings(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "include_health_warnings", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        NotificationSignal name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="onApplicationUpdate")
    def on_application_update(self) -> Optional[pulumi.Input[bool]]:
        """
        On application update flag.
        """
        return pulumi.get(self, "on_application_update")

    @on_application_update.setter
    def on_application_update(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_application_update", value)

    @property
    @pulumi.getter(name="onDownload")
    def on_download(self) -> Optional[pulumi.Input[bool]]:
        """
        On download flag.
        """
        return pulumi.get(self, "on_download")

    @on_download.setter
    def on_download(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_download", value)

    @property
    @pulumi.getter(name="onEpisodeFileDelete")
    def on_episode_file_delete(self) -> Optional[pulumi.Input[bool]]:
        """
        On episode file delete flag.
        """
        return pulumi.get(self, "on_episode_file_delete")

    @on_episode_file_delete.setter
    def on_episode_file_delete(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_episode_file_delete", value)

    @property
    @pulumi.getter(name="onEpisodeFileDeleteForUpgrade")
    def on_episode_file_delete_for_upgrade(self) -> Optional[pulumi.Input[bool]]:
        """
        On episode file delete for upgrade flag.
        """
        return pulumi.get(self, "on_episode_file_delete_for_upgrade")

    @on_episode_file_delete_for_upgrade.setter
    def on_episode_file_delete_for_upgrade(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_episode_file_delete_for_upgrade", value)

    @property
    @pulumi.getter(name="onGrab")
    def on_grab(self) -> Optional[pulumi.Input[bool]]:
        """
        On grab flag.
        """
        return pulumi.get(self, "on_grab")

    @on_grab.setter
    def on_grab(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_grab", value)

    @property
    @pulumi.getter(name="onHealthIssue")
    def on_health_issue(self) -> Optional[pulumi.Input[bool]]:
        """
        On health issue flag.
        """
        return pulumi.get(self, "on_health_issue")

    @on_health_issue.setter
    def on_health_issue(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_health_issue", value)

    @property
    @pulumi.getter(name="onHealthRestored")
    def on_health_restored(self) -> Optional[pulumi.Input[bool]]:
        """
        On health restored flag.
        """
        return pulumi.get(self, "on_health_restored")

    @on_health_restored.setter
    def on_health_restored(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_health_restored", value)

    @property
    @pulumi.getter(name="onManualInteractionRequired")
    def on_manual_interaction_required(self) -> Optional[pulumi.Input[bool]]:
        """
        On manual interaction required flag.
        """
        return pulumi.get(self, "on_manual_interaction_required")

    @on_manual_interaction_required.setter
    def on_manual_interaction_required(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_manual_interaction_required", value)

    @property
    @pulumi.getter(name="onSeriesAdd")
    def on_series_add(self) -> Optional[pulumi.Input[bool]]:
        """
        On series add flag.
        """
        return pulumi.get(self, "on_series_add")

    @on_series_add.setter
    def on_series_add(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_series_add", value)

    @property
    @pulumi.getter(name="onSeriesDelete")
    def on_series_delete(self) -> Optional[pulumi.Input[bool]]:
        """
        On series delete flag.
        """
        return pulumi.get(self, "on_series_delete")

    @on_series_delete.setter
    def on_series_delete(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_series_delete", value)

    @property
    @pulumi.getter(name="onUpgrade")
    def on_upgrade(self) -> Optional[pulumi.Input[bool]]:
        """
        On upgrade flag.
        """
        return pulumi.get(self, "on_upgrade")

    @on_upgrade.setter
    def on_upgrade(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "on_upgrade", value)

    @property
    @pulumi.getter
    def port(self) -> Optional[pulumi.Input[int]]:
        """
        Port.
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "port", value)

    @property
    @pulumi.getter(name="receiverId")
    def receiver_id(self) -> Optional[pulumi.Input[str]]:
        """
        Receiver ID.
        """
        return pulumi.get(self, "receiver_id")

    @receiver_id.setter
    def receiver_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "receiver_id", value)

    @property
    @pulumi.getter(name="senderNumber")
    def sender_number(self) -> Optional[pulumi.Input[str]]:
        """
        Sender Number.
        """
        return pulumi.get(self, "sender_number")

    @sender_number.setter
    def sender_number(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "sender_number", value)

    @property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]:
        """
        List of associated tags.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]):
        pulumi.set(self, "tags", value)

    @property
    @pulumi.getter(name="useSsl")
    def use_ssl(self) -> Optional[pulumi.Input[bool]]:
        """
        Use SSL flag.
        """
        return pulumi.get(self, "use_ssl")

    @use_ssl.setter
    def use_ssl(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "use_ssl", value)


class Signal(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auth_password: Optional[pulumi.Input[str]] = None,
                 auth_username: Optional[pulumi.Input[str]] = None,
                 host: Optional[pulumi.Input[str]] = None,
                 include_health_warnings: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 on_application_update: Optional[pulumi.Input[bool]] = None,
                 on_download: Optional[pulumi.Input[bool]] = None,
                 on_episode_file_delete: Optional[pulumi.Input[bool]] = None,
                 on_episode_file_delete_for_upgrade: Optional[pulumi.Input[bool]] = None,
                 on_grab: Optional[pulumi.Input[bool]] = None,
                 on_health_issue: Optional[pulumi.Input[bool]] = None,
                 on_health_restored: Optional[pulumi.Input[bool]] = None,
                 on_manual_interaction_required: Optional[pulumi.Input[bool]] = None,
                 on_series_add: Optional[pulumi.Input[bool]] = None,
                 on_series_delete: Optional[pulumi.Input[bool]] = None,
                 on_upgrade: Optional[pulumi.Input[bool]] = None,
                 port: Optional[pulumi.Input[int]] = None,
                 receiver_id: Optional[pulumi.Input[str]] = None,
                 sender_number: Optional[pulumi.Input[str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 use_ssl: Optional[pulumi.Input[bool]] = None,
                 __props__=None):
        """
        <!-- subcategory:Notifications -->
        Notification Signal resource.
        For more information refer to [Notification](https://wiki.servarr.com/sonarr/settings#connect) and [Signal](https://wiki.servarr.com/sonarr/supported#signal).

        ## Example Usage

        ```python
        import pulumi
        import pulumi_sonarr as sonarr

        example = sonarr.notifications.Signal("example",
            auth_password="Password",
            auth_username="User",
            host="localhost",
            include_health_warnings=False,
            on_application_update=False,
            on_download=True,
            on_episode_file_delete=False,
            on_episode_file_delete_for_upgrade=True,
            on_grab=False,
            on_health_issue=False,
            on_series_delete=False,
            on_upgrade=True,
            port=8080,
            receiver_id="4321",
            sender_number="1234",
            use_ssl=True)
        ```

        ## Import

        import using the API/UI ID

        ```sh
         $ pulumi import sonarr:Notifications/signal:Signal example 1
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] auth_password: Password.
        :param pulumi.Input[str] auth_username: Username.
        :param pulumi.Input[str] host: Host.
        :param pulumi.Input[bool] include_health_warnings: Include health warnings.
        :param pulumi.Input[str] name: NotificationSignal name.
        :param pulumi.Input[bool] on_application_update: On application update flag.
        :param pulumi.Input[bool] on_download: On download flag.
        :param pulumi.Input[bool] on_episode_file_delete: On episode file delete flag.
        :param pulumi.Input[bool] on_episode_file_delete_for_upgrade: On episode file delete for upgrade flag.
        :param pulumi.Input[bool] on_grab: On grab flag.
        :param pulumi.Input[bool] on_health_issue: On health issue flag.
        :param pulumi.Input[bool] on_health_restored: On health restored flag.
        :param pulumi.Input[bool] on_manual_interaction_required: On manual interaction required flag.
        :param pulumi.Input[bool] on_series_add: On series add flag.
        :param pulumi.Input[bool] on_series_delete: On series delete flag.
        :param pulumi.Input[bool] on_upgrade: On upgrade flag.
        :param pulumi.Input[int] port: Port.
        :param pulumi.Input[str] receiver_id: Receiver ID.
        :param pulumi.Input[str] sender_number: Sender Number.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] tags: List of associated tags.
        :param pulumi.Input[bool] use_ssl: Use SSL flag.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SignalArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        <!-- subcategory:Notifications -->
        Notification Signal resource.
        For more information refer to [Notification](https://wiki.servarr.com/sonarr/settings#connect) and [Signal](https://wiki.servarr.com/sonarr/supported#signal).

        ## Example Usage

        ```python
        import pulumi
        import pulumi_sonarr as sonarr

        example = sonarr.notifications.Signal("example",
            auth_password="Password",
            auth_username="User",
            host="localhost",
            include_health_warnings=False,
            on_application_update=False,
            on_download=True,
            on_episode_file_delete=False,
            on_episode_file_delete_for_upgrade=True,
            on_grab=False,
            on_health_issue=False,
            on_series_delete=False,
            on_upgrade=True,
            port=8080,
            receiver_id="4321",
            sender_number="1234",
            use_ssl=True)
        ```

        ## Import

        import using the API/UI ID

        ```sh
         $ pulumi import sonarr:Notifications/signal:Signal example 1
        ```

        :param str resource_name: The name of the resource.
        :param SignalArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SignalArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auth_password: Optional[pulumi.Input[str]] = None,
                 auth_username: Optional[pulumi.Input[str]] = None,
                 host: Optional[pulumi.Input[str]] = None,
                 include_health_warnings: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 on_application_update: Optional[pulumi.Input[bool]] = None,
                 on_download: Optional[pulumi.Input[bool]] = None,
                 on_episode_file_delete: Optional[pulumi.Input[bool]] = None,
                 on_episode_file_delete_for_upgrade: Optional[pulumi.Input[bool]] = None,
                 on_grab: Optional[pulumi.Input[bool]] = None,
                 on_health_issue: Optional[pulumi.Input[bool]] = None,
                 on_health_restored: Optional[pulumi.Input[bool]] = None,
                 on_manual_interaction_required: Optional[pulumi.Input[bool]] = None,
                 on_series_add: Optional[pulumi.Input[bool]] = None,
                 on_series_delete: Optional[pulumi.Input[bool]] = None,
                 on_upgrade: Optional[pulumi.Input[bool]] = None,
                 port: Optional[pulumi.Input[int]] = None,
                 receiver_id: Optional[pulumi.Input[str]] = None,
                 sender_number: Optional[pulumi.Input[str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 use_ssl: Optional[pulumi.Input[bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SignalArgs.__new__(SignalArgs)

            __props__.__dict__["auth_password"] = None if auth_password is None else pulumi.Output.secret(auth_password)
            __props__.__dict__["auth_username"] = auth_username
            if host is None and not opts.urn:
                raise TypeError("Missing required property 'host'")
            __props__.__dict__["host"] = host
            __props__.__dict__["include_health_warnings"] = include_health_warnings
            __props__.__dict__["name"] = name
            __props__.__dict__["on_application_update"] = on_application_update
            __props__.__dict__["on_download"] = on_download
            __props__.__dict__["on_episode_file_delete"] = on_episode_file_delete
            __props__.__dict__["on_episode_file_delete_for_upgrade"] = on_episode_file_delete_for_upgrade
            __props__.__dict__["on_grab"] = on_grab
            __props__.__dict__["on_health_issue"] = on_health_issue
            __props__.__dict__["on_health_restored"] = on_health_restored
            __props__.__dict__["on_manual_interaction_required"] = on_manual_interaction_required
            __props__.__dict__["on_series_add"] = on_series_add
            __props__.__dict__["on_series_delete"] = on_series_delete
            __props__.__dict__["on_upgrade"] = on_upgrade
            __props__.__dict__["port"] = port
            if receiver_id is None and not opts.urn:
                raise TypeError("Missing required property 'receiver_id'")
            __props__.__dict__["receiver_id"] = receiver_id
            if sender_number is None and not opts.urn:
                raise TypeError("Missing required property 'sender_number'")
            __props__.__dict__["sender_number"] = None if sender_number is None else pulumi.Output.secret(sender_number)
            __props__.__dict__["tags"] = tags
            __props__.__dict__["use_ssl"] = use_ssl
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["authPassword", "senderNumber"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Signal, __self__).__init__(
            'sonarr:Notifications/signal:Signal',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            auth_password: Optional[pulumi.Input[str]] = None,
            auth_username: Optional[pulumi.Input[str]] = None,
            host: Optional[pulumi.Input[str]] = None,
            include_health_warnings: Optional[pulumi.Input[bool]] = None,
            name: Optional[pulumi.Input[str]] = None,
            on_application_update: Optional[pulumi.Input[bool]] = None,
            on_download: Optional[pulumi.Input[bool]] = None,
            on_episode_file_delete: Optional[pulumi.Input[bool]] = None,
            on_episode_file_delete_for_upgrade: Optional[pulumi.Input[bool]] = None,
            on_grab: Optional[pulumi.Input[bool]] = None,
            on_health_issue: Optional[pulumi.Input[bool]] = None,
            on_health_restored: Optional[pulumi.Input[bool]] = None,
            on_manual_interaction_required: Optional[pulumi.Input[bool]] = None,
            on_series_add: Optional[pulumi.Input[bool]] = None,
            on_series_delete: Optional[pulumi.Input[bool]] = None,
            on_upgrade: Optional[pulumi.Input[bool]] = None,
            port: Optional[pulumi.Input[int]] = None,
            receiver_id: Optional[pulumi.Input[str]] = None,
            sender_number: Optional[pulumi.Input[str]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
            use_ssl: Optional[pulumi.Input[bool]] = None) -> 'Signal':
        """
        Get an existing Signal resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] auth_password: Password.
        :param pulumi.Input[str] auth_username: Username.
        :param pulumi.Input[str] host: Host.
        :param pulumi.Input[bool] include_health_warnings: Include health warnings.
        :param pulumi.Input[str] name: NotificationSignal name.
        :param pulumi.Input[bool] on_application_update: On application update flag.
        :param pulumi.Input[bool] on_download: On download flag.
        :param pulumi.Input[bool] on_episode_file_delete: On episode file delete flag.
        :param pulumi.Input[bool] on_episode_file_delete_for_upgrade: On episode file delete for upgrade flag.
        :param pulumi.Input[bool] on_grab: On grab flag.
        :param pulumi.Input[bool] on_health_issue: On health issue flag.
        :param pulumi.Input[bool] on_health_restored: On health restored flag.
        :param pulumi.Input[bool] on_manual_interaction_required: On manual interaction required flag.
        :param pulumi.Input[bool] on_series_add: On series add flag.
        :param pulumi.Input[bool] on_series_delete: On series delete flag.
        :param pulumi.Input[bool] on_upgrade: On upgrade flag.
        :param pulumi.Input[int] port: Port.
        :param pulumi.Input[str] receiver_id: Receiver ID.
        :param pulumi.Input[str] sender_number: Sender Number.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] tags: List of associated tags.
        :param pulumi.Input[bool] use_ssl: Use SSL flag.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SignalState.__new__(_SignalState)

        __props__.__dict__["auth_password"] = auth_password
        __props__.__dict__["auth_username"] = auth_username
        __props__.__dict__["host"] = host
        __props__.__dict__["include_health_warnings"] = include_health_warnings
        __props__.__dict__["name"] = name
        __props__.__dict__["on_application_update"] = on_application_update
        __props__.__dict__["on_download"] = on_download
        __props__.__dict__["on_episode_file_delete"] = on_episode_file_delete
        __props__.__dict__["on_episode_file_delete_for_upgrade"] = on_episode_file_delete_for_upgrade
        __props__.__dict__["on_grab"] = on_grab
        __props__.__dict__["on_health_issue"] = on_health_issue
        __props__.__dict__["on_health_restored"] = on_health_restored
        __props__.__dict__["on_manual_interaction_required"] = on_manual_interaction_required
        __props__.__dict__["on_series_add"] = on_series_add
        __props__.__dict__["on_series_delete"] = on_series_delete
        __props__.__dict__["on_upgrade"] = on_upgrade
        __props__.__dict__["port"] = port
        __props__.__dict__["receiver_id"] = receiver_id
        __props__.__dict__["sender_number"] = sender_number
        __props__.__dict__["tags"] = tags
        __props__.__dict__["use_ssl"] = use_ssl
        return Signal(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="authPassword")
    def auth_password(self) -> pulumi.Output[str]:
        """
        Password.
        """
        return pulumi.get(self, "auth_password")

    @property
    @pulumi.getter(name="authUsername")
    def auth_username(self) -> pulumi.Output[str]:
        """
        Username.
        """
        return pulumi.get(self, "auth_username")

    @property
    @pulumi.getter
    def host(self) -> pulumi.Output[str]:
        """
        Host.
        """
        return pulumi.get(self, "host")

    @property
    @pulumi.getter(name="includeHealthWarnings")
    def include_health_warnings(self) -> pulumi.Output[bool]:
        """
        Include health warnings.
        """
        return pulumi.get(self, "include_health_warnings")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        NotificationSignal name.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="onApplicationUpdate")
    def on_application_update(self) -> pulumi.Output[bool]:
        """
        On application update flag.
        """
        return pulumi.get(self, "on_application_update")

    @property
    @pulumi.getter(name="onDownload")
    def on_download(self) -> pulumi.Output[bool]:
        """
        On download flag.
        """
        return pulumi.get(self, "on_download")

    @property
    @pulumi.getter(name="onEpisodeFileDelete")
    def on_episode_file_delete(self) -> pulumi.Output[bool]:
        """
        On episode file delete flag.
        """
        return pulumi.get(self, "on_episode_file_delete")

    @property
    @pulumi.getter(name="onEpisodeFileDeleteForUpgrade")
    def on_episode_file_delete_for_upgrade(self) -> pulumi.Output[bool]:
        """
        On episode file delete for upgrade flag.
        """
        return pulumi.get(self, "on_episode_file_delete_for_upgrade")

    @property
    @pulumi.getter(name="onGrab")
    def on_grab(self) -> pulumi.Output[bool]:
        """
        On grab flag.
        """
        return pulumi.get(self, "on_grab")

    @property
    @pulumi.getter(name="onHealthIssue")
    def on_health_issue(self) -> pulumi.Output[bool]:
        """
        On health issue flag.
        """
        return pulumi.get(self, "on_health_issue")

    @property
    @pulumi.getter(name="onHealthRestored")
    def on_health_restored(self) -> pulumi.Output[bool]:
        """
        On health restored flag.
        """
        return pulumi.get(self, "on_health_restored")

    @property
    @pulumi.getter(name="onManualInteractionRequired")
    def on_manual_interaction_required(self) -> pulumi.Output[bool]:
        """
        On manual interaction required flag.
        """
        return pulumi.get(self, "on_manual_interaction_required")

    @property
    @pulumi.getter(name="onSeriesAdd")
    def on_series_add(self) -> pulumi.Output[bool]:
        """
        On series add flag.
        """
        return pulumi.get(self, "on_series_add")

    @property
    @pulumi.getter(name="onSeriesDelete")
    def on_series_delete(self) -> pulumi.Output[bool]:
        """
        On series delete flag.
        """
        return pulumi.get(self, "on_series_delete")

    @property
    @pulumi.getter(name="onUpgrade")
    def on_upgrade(self) -> pulumi.Output[bool]:
        """
        On upgrade flag.
        """
        return pulumi.get(self, "on_upgrade")

    @property
    @pulumi.getter
    def port(self) -> pulumi.Output[int]:
        """
        Port.
        """
        return pulumi.get(self, "port")

    @property
    @pulumi.getter(name="receiverId")
    def receiver_id(self) -> pulumi.Output[str]:
        """
        Receiver ID.
        """
        return pulumi.get(self, "receiver_id")

    @property
    @pulumi.getter(name="senderNumber")
    def sender_number(self) -> pulumi.Output[str]:
        """
        Sender Number.
        """
        return pulumi.get(self, "sender_number")

    @property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Sequence[int]]:
        """
        List of associated tags.
        """
        return pulumi.get(self, "tags")

    @property
    @pulumi.getter(name="useSsl")
    def use_ssl(self) -> pulumi.Output[bool]:
        """
        Use SSL flag.
        """
        return pulumi.get(self, "use_ssl")

