from .types import ObjectDetectionPostProcessParams

def hailo_yolov3_post_process(params: ObjectDetectionPostProcessParams): ...
def hailo_ssd_post_process(params: ObjectDetectionPostProcessParams): ...
