# coding: utf-8

class _Hash:
    def update(self, data: str) -> None: ...
    def hexdigest(self) -> str: ...

def md5() -> _Hash: ...
def sha1() -> _Hash: ...
def sha256() -> _Hash: ...
def sha512() -> _Hash: ...